// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypilfkocaslbbygvaprn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwaWxma29jYXNsYmJ5Z3ZhcHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTE5NjgsImV4cCI6MjA2NTU2Nzk2OH0.uh_G3FP3aunlZWbOBG1QQW6_njUwcRFRtSyW5K3l6HI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);